### ISSUE TITLE
Add OpenBabel to tests

### ISSUE THREAD

**Issue by espottesmith** [materialsproject/mrnet#11]
Many of our current tests skip if OpenBabel is not present, but OpenBabel is not currently being installed during testing.

This was/is also a problem in pymatgen. Basically, installing OpenBabel from pip will not work because you also need the C/C++ bindings, and I couldn't figure out a way to get it to install from conda.

This is probably going to be a huge pain, but if someone can figure it out, it'll make our testing suite far more robust than it currently is.

I guess we could also rewrite our tests to be less reliant on OpenBabel. That might be easier, but also less desirable since we use the Babel-based NearNeighbor class everywhere in production.

**Comment by shyamd** [comment]
Fixed in #12
